apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-dp
  labels:
    app: production

spec:
  replicas: 2
  selector:
    matchLabels:
      app: production
  template:
    metadata:
      name: jenkins-prod
      labels:
        app: production
    spec:
      containers:
        - name: jenkins
          image: jenkins:2.60.3-alpine
    